### ISSUE TITLE
Nuevas funcionalidades

### ISSUE THREAD

**Issue by dagoull** [edujbarrios/Metaheuristics-for-Logistics#1]
-Implementar una funcionalidad que permita al usuario seleccionar el archivo de datos a través de la entrada del teclado.
-Implementar una funcionalidad que permita al usuario seleccionar el archivo de datos a través mediante argumentos de línea de comandos.

**Comment by alu0101332819** [comment]
Las funcionalidades demandadas han sido implementadas correctamente en el proyecto.
