### ISSUE TITLE
Pruebas

### ISSUE THREAD

**Issue by dcastellnieves** [edujbarrios/Metaheuristics-for-Logistics#3]
Debemos construir las pruebas que dan soporte a las funcionalidades del proyecto.
Darle soporte en **sonarcloud.io** a Coverage.

**Comment by edujbarrios** [comment]
Dado soporto a coverage en sonarcloud.io

**Comment by edujbarrios** [comment]
## Actualización: Solución del Problema de Paquetes en el Proyecto con Maven

Se ha logrado arreglar un problema significativo en el manejo de paquetes dentro del proyecto. El origen del problema parece haber sido durante la migración a Maven, específicamente con la ruta `/src/main/java`, que es crucial para el funcionamiento adecuado de Maven. Se identificó que la carpeta "java" estaba siendo reconocida incorrectamente como un paquete de nombre "java".

Este malentendido causaba interferencias en el funcionamiento general del proyecto, impactando especialmente los imports de los paquetes en `/src/`. Este problema generaba fallos en cascada, afectando las pruebas unitarias con errores de importación, ya que en ´/test` también se debían hacer imports de la misma naturaleza.

Adicionalmente, la estructura de nuestro código, compuesta mayormente por clases abstractas y una cantidad considerable de métodos privados, complicará la creación de pruebas unitarias efectivas.

Ahora que este problema fundamental ha sido resuelto, nuestro enfoque se centrará en realizar pruebas unitarias en los próximos días. El objetivo es alcanzar la mayor cobertura de código posible, aunque reconocemos que llegar al 100% podría ser improbable debido a la naturaleza de nuestro código.
