### ISSUE TITLE
Funcionalidades

### ISSUE THREAD

**Issue by dcastellnieves** [edujbarrios/Metaheuristics-for-Logistics#6]
¿Donde encuentro las funcionalidades que se indicaron ?

**Comment by alu0101332819** [comment]
Las funcionalidades demandadas anteriormente que constaban de:
-Implementar una funcionalidad que permita al usuario seleccionar el archivo de datos a través de la entrada del teclado.
-Implementar una funcionalidad que permita al usuario seleccionar el archivo de datos a través mediante argumentos de línea de comandos.
Se pueden ver resueltas a la hora de ejecutar el programa, tanto mediante línea de comandos añadiendo el fichero .txt deseado en forma de argumento justo antes de comenzar la ejecución del programa, como realizando la ejecución del programa sin argumentos, lo que hará que, una vez en ejecución, se pida al usuario mediante entrada del teclado el fichero .txt deseado.
